spring:
  application:
    name: eureka

security:
  basic:
    enable: true
  user:
    name: root
    password: 123456

# server:
#   port: 8761
# eureka:
#   client:
#     registerWithEureka: false
#     fetchRegistry: false
#     serviceUrl:
#       defaultZone: http://127.0.0.1:8761/eureka/


---
spring:
  profiles: 1
server:
  port: 10001
eureka:
  instance:
    hostname: 1.eureka.com
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://root:123456@2.eureka.com:10002/eureka/,http://root:123456@3.eureka.com:10003/eureka/
      
---
spring:
  profiles: 2
server:
  port: 10002
eureka:
  instance:
    hostname: 2.eureka.com
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://root:123456@1.eureka.com:10001/eureka/,http://root:123456@3.eureka.com:10003/eureka/

---
spring:
  profiles: 3
server:
  port: 10003
eureka:
  instance:
    hostname: 3.eureka.com
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://root:123456@1.eureka.com:10001/eureka/,http://root:123456@2.eureka.com:10002/eureka/